// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Product struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       int32     `json:"price"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ProductImage struct {
	ID        int64  `json:"id"`
	ProductID int64  `json:"product_id"`
	Path      string `json:"path"`
}

type User struct {
	ID                      int64          `json:"id"`
	Email                   string         `json:"email"`
	Password                string         `json:"password"`
	FirstName               sql.NullString `json:"first_name"`
	LastName                sql.NullString `json:"last_name"`
	AccessLevel             int32          `json:"access_level"`
	IsActive                int32          `json:"is_active"`
	ActivationToken         sql.NullString `json:"activation_token"`
	ActivationExpiration    sql.NullTime   `json:"activation_expiration"`
	PasswordResetToken      sql.NullString `json:"password_reset_token"`
	PasswordResetExpiration sql.NullTime   `json:"password_reset_expiration"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}
