// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID                      int64
	Email                   string
	Password                string
	FirstName               sql.NullString
	LastName                sql.NullString
	AccessLevel             int32
	IsActive                int32
	ActivationToken         sql.NullString
	ActivationExpiration    sql.NullTime
	PasswordResetToken      sql.NullString
	PasswordResetExpiration sql.NullTime
	CreatedAt               time.Time
	UpdatedAt               time.Time
}
