// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: products.sql

package db

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO
    products (user_id, title, description, price)
VALUES
    (?, ?, ?, ?)
`

type CreateProductParams struct {
	UserID      int64
	Title       string
	Description string
	Price       int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProduct,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Price,
	)
}

const createProductImage = `-- name: CreateProductImage :execresult
INSERT INTO
    products_images (product_id, path)
VALUES
    (?, ?)
`

type CreateProductImageParams struct {
	ProductID int64
	Path      string
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProductImage, arg.ProductID, arg.Path)
}
